#!/bin/bash

# Scale deployment to 3 replicas
kubectl scale deployment messaging-app --replicas=3

# Verify pods
kubectl get pods

# Note: 'wrk' might not be installed. Assuming it is or just logging command.
echo "Running load test (ensure wrk is installed)..."
# wrk -t12 -c400 -d30s http://<minikube-ip>:SERVICE_PORT

# Monitor resource usage (requires metrics-server usually)
kubectl top pods
